### ISSUE TITLE
State is not defined - TypeError: Expected one of the following types text|select-one|select-multiple

### ISSUE THREAD

**Issue by michalcharvat** [filamentphp/filament#3550]
### Package

filament/forms

### Package Version

v2.15.19

### Laravel Version

v9.25.1

### Livewire Version

v2.15.19

### PHP Version

PHP 8.1.6

### Problem description

After update to latest forms and laravel version there is the error displaying multiselect fields (and probably any other fields based on select. Before this update there was similar issue with reactive fields which dissapear. 

As you can see on following picture, state is defined as wire.entagle
<img width="287" alt="image" src="https://user-images.githubusercontent.com/8058273/185437112-f90eba79-1f3e-4df5-86df-f9571c98e33c.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/8058273/185438307-f71b9a9f-6f76-4bc3-870e-4a01d287652a.png">

<img width="560" alt="image" src="https://user-images.githubusercontent.com/8058273/185438981-192dd20a-c590-45c9-b10e-3c5ed8dcec15.png">

### Expected behavior

-

### Steps to reproduce

Just put the Multiselect to getFormSchema

### Reproduction repository

-

**Comment by danharrin** [comment]
I cannot reproduce this, so we will need a reproduction repo as described above to continue. Please edit your original post and the issue should reopen, lmk if not.

**Comment by michalcharvat** [comment]
I am looking on it right now. Only what I can say it has something to do with the relationship. When I remove it multiselect is rendered well with all options. I will try create repo over the weekend.

**Comment by mstfkhazaal** [comment]
@michalcharvat Did you find any solution?  I suffer from the same problem
My issue https://github.com/filamentphp/filament/issues/6248#issue-1672849756

**Comment by michalcharvat** [comment]
> @michalcharvat Did you find any solution? I suffer from the same problem My issue [#6248 (comment)](https://github.com/filamentphp/filament/issues/6248#issue-1672849756)

@mstfkhazaal  Not really. I had stored older version in git so I just discard changes and used older version which worked like a charm. Not sure what I will do if client needs update to latest :D

**Comment by nbaasmf** [comment]
I have the same problem. Are there any workarounds yet?

**Comment by danharrin** [comment]
If any of you provide the reproduction repository we asked for, we can investigate what you're doing wrong. But I'm not wasting time trying to fix a bug I cant reproduce.

**Comment by nbaasmf** [comment]
This repo shows a simple example of the bug. It has a Form `PostForm` for the model `Post`. `Post` has 2 relations: `category` and `subcategory`. Each `subcategory` belongs to a `category`.

https://github.com/nbaasmf/filament-issue-example

- clone
- composer install
- sail up
- npm install && npm run build
- artisan migrate --seed
- open localhost/posts/1/edit

Now in the form, I have 2 relationship select fields. One for Category and one for Subcategory. What I want now is that the subcategory select is filled depending on the value of the category select. This is pretty much the same situation as in [this video here](https://filamentphp.com/docs/2.x/forms/advanced#dependant-fields--components). Subcategory is reactive, Category has an `afterStateUpdated` callback. Both are preloaded and searchable.

Changing Category behaves as expected. Changing Subcategory however breaks the Selects as seen in the video.

Some other thingts I've noticed:

- removing `searchable()` fixes the problem ( probably because the select is now natively rendered)
- I've experienced the same error with searchable selects that are not dependant. They don't break on change, but instead on submit. Re-filling the form with `$this->form->fill($this->post->toArray())` in the submit function after saving the post fixed that isssue

https://github.com/filamentphp/filament/assets/121862830/b7e284a1-71f9-470d-a47f-7193c1b971a6

![chrome_tN3wj3ElPw](https://github.com/filamentphp/filament/assets/121862830/c211504d-aa91-4c70-bfaa-62224cecf44a)


BTW these are my versions:

- filament/forms v2.17.38
- filament/notifications v2.17.38
- filament/support v2.17.38
- laravel/framework v10.10.0
- livewire/livewire v2.12.3
- alpinejs v3.12.0

**Comment by danharrin** [comment]
1) You don't have Livewire class properties defined for each field. These are in the documentation.
2) You are filling the form from `->toArray()`, but since the `id` field is being returned as part of the array, it's overriding the Livewire component's `$id` property, causing the error.

To fix both of these issues, create a `public $data = []` property. Then, define `getFormStatePath()` and `return 'data'`.

This will store all form data in the `$data` array, and there is no concern about the Livewire component ID being overwritten.

**Comment by nbaasmf** [comment]
That worked perfectly :) Thank you very much for your time and the quick response!
