### ISSUE TITLE
mutateFormDataBeforeSave doesn't work on ManageRecords

### ISSUE THREAD

**Issue by cobraprojects** [filamentphp/filament#3637]
### Package

filament/filament

### Package Version

v2.15.24

### Laravel Version

v9.26.1

### Livewire Version

v2

### PHP Version

PHP 8.1

### Problem description

`mutateFormDataBeforeSave` doesn't work on ManageRecords

I created a simple resource
add `mutateFormDataBeforeSave`  to `Pages/ManageResource.php`

```
protected function mutateFormDataBeforeSave(array $data): array
  {
      $data['competed_by'] = $data['completed'] == true ? auth()->id() : null;

      return $data;
  }
```

it doesn't work

### Expected behavior

on save it should use the same Edit and create actions as full resource

### Steps to reproduce

1- create a simple filament resource 
2- try to ->mutate form data

### Reproduction repository

https://github.com/cobraprojects/filament-test

**Comment by danharrin** [comment]
Hello! Thats because the mutate* functions exist on specific page classes like Edit, not resources classes in general.

In this case, since you just have a List/Manage page, you can use actions to customise this - https://filamentphp.com/docs/2.x/admin/resources/listing-records#customizing-data-before-saving-1
