### ISSUE TITLE
Disabled Select field still shows "Select an option" text

### ISSUE THREAD

**Issue by amsnvc** [filamentphp/filament#4012]
### Package

filament/filament

### Package Version

v2.16.1

### Laravel Version

v9.29.0

### PHP Version

PHP 8.1

### Problem description

Having a disabled Select::make() field still shows the "Select an option" text.

```php
Forms\Components\Select::make('roles')
    ->relationship('roles', 'label')
    ->dehydrated(false)
    ->disabled()
    ->multiple(),
```

![grafik](https://user-images.githubusercontent.com/89933034/190085993-b44adecf-ab2a-44bd-9df0-64b94f51fcdf.png)

### Expected behavior

If the field is disabled, the "Select an option" text shouldnt't show up. 

### Steps to reproduce

Having a disabled multiple Select::make() field.

```php
Forms\Components\Select::make('name')
    ->disabled()
    ->multiple(),
```

### Reproduction repository

https://github.com/

**Comment by zepfietje** [comment]
What would you expect the placeholder to show instead?

**Comment by amsnvc** [comment]
> What would you expect the placeholder to show instead?

The "Wählen Sie eine Option" (Select an Option) text shouldn't show up at all when the field is disabled. I asked this in the discord and was told I should open an issue on this as this shouldn't happen😅

**Comment by danharrin** [comment]
I'm reevaluating if I was correct by saying that 😅 I guess it would actually be inconsistent with the rest of the fields

**Comment by zepfietje** [comment]
> I guess it would actually be inconsistent with the rest of the fields

That's my concern as well.

You could always set a custom placeholder for your specific case, right, @amsnvc?

**Comment by judgej** [comment]
Is this the same problem? The filter for a table, set as `multiple select` with no override of the placeholder looks like this after filter options have been selected. I would expect the default "All" to disappear, since the filter is no longer, technically, "All". I cannot see a way to manually remove the placeholder once one or more selections have been made.

![image](https://github.com/filamentphp/filament/assets/395934/30971787-c4e4-41d5-b4b2-17fdfaae3a49)

My immediate workaround is to replace "All" with something that makes more sense if it remains, but "All" is nice - clean, little to read, easy to scan.

**Comment by danharrin** [comment]
@judgej that issue is probably #2363

**Comment by judgej** [comment]
This issue is about the placeholder text not hidign when it is expected to, on a multi-select form item, if I understand correctly. My example is the same symptom, but for a table filter, which ultimately is based on the same form multi-select.

So, this issue is closed, so does that mean the placeholder text is not supposed to hide once options have been selected? Or is there I fix here I can't see? Or is it just my installation?

What is is supposed to do? My understanding is that placeholders are there in a field, only until the field has something in it, then the placeholder should be gone.

**Comment by danharrin** [comment]
Its expected behaviour I think from Choices.js? Maybe I'm wrong

**Comment by judgej** [comment]
It was asked in 2019, with some nasty (as in, not wanting to get involved in) JS to fix it. It's a feature request from 2020 too. Neither have been addressed.

https://github.com/Choices-js/Choices/issues/770

Just realised this issue started with "disabled", so different to my problem. Exactly the same other than being different.

Also noticed in the docs that a placeholder for a single select is implemented as an empty string value option. If your options include one with an empty string, then it will mess with the placeholder). Just something to be aware of.

**Comment by danharrin** [comment]
The placeholder is the null/empty string version, for consistency with the non-searchable option.

**Comment by Narek1331** [comment]
->selectablePlaceholder(false)
