### ISSUE TITLE
Multi-context / guard

### ISSUE THREAD

**Issue by danharrin** [filamentphp/filament#4177]
### Discussed in https://github.com/filamentphp/filament/discussions/4173

<div type='discussions-op-text'>

<sup>Originally posted by **enso-media** September 23, 2022</sup>
Right now its not possible to register different resources based on specific user roles.
The user data is only available when the StartSession middleware was executed, however registration of filament resources is only possible early from within a service provider which runs before.
Trying to use Filament::registerResource() at later times, will result in "route not defined" errors.</div>

**Comment by Nuhel** [comment]
I have make something like this,
It was my client requirements to manage navigation menu, It may not prevent registering the resource , but navigation menu can be manipulated.

Here is a link of a video of this.
[https://drive.google.com/file/d/1ulLsGdR5nVsz1g2XVAzpqC6gBVZd6fbE/view?usp=sharing](url)

**Comment by enso-media** [comment]
> but navigation menu can be manipulated.
Sure, this is already possible out of the box with the NavigationBuilder.

However i need completely separated resources, pages and functions for specific application scopes and roles (admin/tenant/user).
We already have methods for this like registerResources, registerPages and registerWidgets. The issue is just that you cannot use those methods later, as the filament routes get generated separately already from within the register method in the service provider.

**Comment by mikeldoka1** [comment]
I personally think this is the missing piece for filament. I will try and make use of plugins for now

**Comment by danharrin** [comment]
Completed now, it will be available in v3 :)
